### ISSUE TITLE
Problems running spsim

### ISSUE THREAD

**Issue by FilipeMaia** [mhantke/condor#3]
Alberto was trying to run a simulation with spsim and the following thing showed up problem in the slurm.out:

INFO:simulate:Simulation with spsim started. (PROGSTAT)
/home/www/condor/local/bin/spsim: error while loading shared libraries: libcudart.so.6.5: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/www/condor/diffractor/diffractor/simulate.py", line 119, in <module>
    conf = read_configuration_spsim("./spsim.confout")
  File "/home/www/condor/diffractor/diffractor/simulate.py", line 19, in read_configuration_spsim
    c = open(filename,"r")
IOError: [Errno 2] No such file or directory: './spsim.confout'

Looks like it couldn't find the CUDA libraries. Is the LD_LIBRARY_PATH correctly set?

**Comment by mhantke** [comment]
The problem lies in different versions of cuda installed on different nodes of the davinci cluster. In particular I found on a001 CUDA 6.5

[root@a001 ~]# ls /usr/local/cuda/lib64/libcudart.so*
/usr/local/cuda/lib64/libcudart.so      /usr/local/cuda/lib64/libcudart.so.6.5.14
/usr/local/cuda/lib64/libcudart.so.6.5

and on c006 CUDA 7.0

[root@c006 ~]# ls /usr/local/cuda/lib64/libcudart.so*
/usr/local/cuda/lib64/libcudart.so      /usr/local/cuda/lib64/libcudart.so.7.0.28
/usr/local/cuda/lib64/libcudart.so.7.0

I think we should make sure that on all nodes is the same cuda version available.
